
project:
  type: website
  output-dir: docs

website:
  title: "Amanda Diah Maharani, MD"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Insights
        href: insights.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    smooth-scroll: true
